### ISSUE TITLE
ARM Template Language server fails to start when using WSL2

### ISSUE THREAD

**Issue by alexpilon666** [microsoft/vscode-azurearmtools#1295]
Does this occur consistently? Yes
Repro steps:

1. Start VS Code
2. VS Code tries to start the `ARM Template Language Server`, fails 5 times in a row, then never tries again

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.15.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.55.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:239:61005extension.bundle.js:239:61005
Object.callWithTelemetryAndErrorHandlingSync extension.bundle.js:16:144558
WrappedErrorHandler.closed extension.bundle.js:239:60851
LanguageClient.handleConnectionClosed vscode-languageclient/client.js:2044:55
LanguageClient.handleConnectionClosed vscode-languageclient/main.js:127:15
closeHandler vscode-languageclient/client.js:2023:18
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
closeHandler vscode-jsonrpc/main.js:226:26
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
StreamMessageReader.fireClose vscode-jsonrpc/messageReader.js:111:27
Socket.<anonymous> vscode-jsonrpc/messageReader.js:151:46
Socket.emit events.js:327:22
Pipe.<anonymous> net.js:674:12
```

<summary>Full stack trace and error</summary>

```
[Info  - 10:51:06 a.m.] Connection to server got closed. Server will restart.
Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at OmniSharp.Extensions.LanguageServer.Protocol.Serialization.Converters.AbsoluteUriConverter.ReadJson(JsonReader reader, Type objectType, Uri existingValue, Boolean hasExistingValue, JsonSerializer serializer)
   at Newtonsoft.Json.JsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(IMethodWithParams instance)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.GetDescriptor(Request request)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.OmniSharp.Extensions.JsonRpc.IRequestRouter<OmniSharp.Extensions.JsonRpc.IHandlerDescriptor>.GetDescriptor(Request request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Error: The connection to the ARM Template Language Server got closed.
```

</details>

**Comment by alexpilon666** [comment]
Solved the issue myself. For others that may get the same issue: Found it the issue started happening once I added other folders in my Workspace; those folders were located in 2 different WSL2 distros. Once those folders were removed and VS Code restarted, issue was solved.

This is still a problem though if we need to run ARM Template Language server on WSL2-based files.

**Comment by StephenWeatherford** [comment]
@alexpilon666 Thanks for taking the time to enter this issue!  I'm out for a couple of weeks then will take a look when I'm able.

**Comment by anttirokka** [comment]
I had the same issue. If i open the folder from \\wsl$ directly, the arm template language server crashes. 

workaround was to map the \\$wsl\ubuntu folder as network drive and open the folder using the mapped drive.

**Comment by StephenWeatherford** [comment]
@anttirokka Thanks for the additional info!

**Comment by alexpilon666** [comment]
@StephenWeatherford any idea when this might get fixed ? I'd like to run ZSH on WSL2, but it sucks big time with the Windows filesystem, so I'd need to move all my ARM code in the Linux filesystem while using VS Code on Windows.
Thanks!

**Comment by StephenWeatherford** [comment]
It's been difficult to get time lately, so good to hear when issues are important, thanks.  I'll try to take a look in the next couple of weeks, but not very familiar with WSL2.  Feel free to make suggestions or even fixes yourself in the meantime.

**Comment by StephenWeatherford** [comment]
Priorities have not been kind for getting time to looking into this.  Any chance someone would like to take a crack at it themselves?

**Comment by PDunbarCGI** [comment]
I think I've identified a work-around for this issue:

1. Open a folder in vscode (instead of the workspace with multiple folders added)
2. Open an ARM template to start the server
3. Open the workspace containing multiple folders
4. Open the ARM template, the language server seems to work as desired for the remainder of the VS Code session

**Comment by StephenWeatherford** [comment]
Triage: Due to changing priorities, I don't see us getting to fix this unless we get more customer upvotes or a customer-provided fix.
