### ISSUE TITLE
ARM Schemas are not loading and the connection to the ARM Template Language Server got closed

### ISSUE THREAD

**Issue by JacquesVenter1976** [microsoft/vscode-azurearmtools#1498]
Does this occur consistently?  Yes
Repro steps:

1. Start VS Code
2. Go to Extensions, validate Azure Resource Manager (ARM) Tools for Visual Studio Code (Preview) is installed and enables
3. Open and ARM template file
4. Click Terminal, New Terminal
5. Select the down arrow and in the dropdown list select PowerShell.

ARM Schema begins to load, but the process never completes and eventually the error listed below appears

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.15.7
OS: linux
OS Release: 5.10.114-16024-gbdf1547bd4f4
Product: Visual Studio Code
Product Version: 1.68.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:209:204152
callWithTelemetryAndErrorHandlingSync extension.bundle.js:16:248270
WrappedErrorHandler.closed extension.bundle.js:209:204035
LanguageClient.handleConnectionClosed extension.bundle.js:16:170156
LanguageClient.handleConnectionClosed extension.bundle.js:209:71022
closeHandler extension.bundle.js:16:168118
CallbackList.invoke vscode-jsonrpc/events.js:55:39
Emitter.fire vscode-jsonrpc/events.js:117:36
closeHandler vscode-jsonrpc/connection.js:256:26
CallbackList.invoke extension.bundle.js:16:310204
Emitter.fire extension.bundle.js:16:310988
StreamMessageReader.fireClose extension.bundle.js:209:143245
Socket.<anonymous> extension.bundle.js:209:144905
```

</details>

**Comment by JacquesVenter1976** [comment]
The following output has been genereated

Using dotnet core executable at /home/cafemonkey2015/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.6/dotnet
Starting ARM Template Language Server at /home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/languageServer/Microsoft.ArmLanguageServer.dll
Language server nuget version: 3.0.0-preview.22255.1
Client options:
{
  "documentSelector": [
    {
      "language": "arm-template",
      "scheme": "file"
    },
    {
      "language": "arm-template",
      "scheme": "untitled"
    }
  ],
  "diagnosticCollectionName": "ARM Template Language Server diagnostics",
  "outputChannel": {
    "name": "Azure Resource Manager Tools",
    "extensionPrefix": "azureResourceManagerTools",
    "_outputChannel": {
      "name": "Azure Resource Manager Tools"
    }
  },
  "revealOutputChannelOn": 3,
  "synchronize": {
    "configurationSection": "azureResourceManagerTools"
  },
  "middleware": {}
}
Server options:
{
  "run": {
    "command": "/home/cafemonkey2015/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.6/dotnet",
    "args": [
      "/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/languageServer/Microsoft.ArmLanguageServer.dll",
      "--logLevel",
      "Warning"
    ],
    "options": {
      "shell": false
    }
  },
  "debug": {
    "command": "/home/cafemonkey2015/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.6/dotnet",
    "args": [
      "/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/languageServer/Microsoft.ArmLanguageServer.dll",
      "--logLevel",
      "Warning"
    ],
    "options": {
      "shell": false
    }
  }
}
Error: The connection to the ARM Template Language Server got closed.
[Info  - 11:35:30 AM] Connection to server got closed. Server will restart.
Error: The connection to the ARM Template Language Server got closed.
[Info  - 11:53:01 AM] Connection to server got closed. Server will restart.
Error: The connection to the ARM Template Language Server got closed.
[Info  - 11:59:36 AM] Connection to server got closed. Server will restart.
Error: The connection to the ARM Template Language Server got closed.
[Info  - 12:10:27 PM] Connection to server got closed. Server will restart.
Error: The connection to the ARM Template Language Server got closed.
[Info  - 12:23:47 PM] Connection to server got closed. Server will restart.
Error: The connection to the ARM Template Language Server got closed.
[Info  - 12:35:39 PM] Connection to server got closed. Server will restart.
[Error - 12:35:39 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/dist/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/dist/extension.bundle.js:16:169842)
	at LanguageClient.handleConnectionClosed (/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/dist/extension.bundle.js:16:170076)
	at LanguageClient.handleConnectionClosed (/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/dist/extension.bundle.js:209:71022)
	at closeHandler (/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/dist/extension.bundle.js:16:168118)
	at CallbackList.invoke (/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/dist/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/dist/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/dist/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/dist/extension.bundle.js:16:310204)
	at Emitter.fire (/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/dist/extension.bundle.js:16:310988)
	at StreamMessageReader.fireClose (/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/dist/extension.bundle.js:209:143245)
	at Socket.<anonymous> (/home/cafemonkey2015/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.7/dist/extension.bundle.js:209:144905)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)
