### ISSUE TITLE
Language Server Error

### ISSUE THREAD

**Issue by mohamedfarees** [microsoft/vscode-azurearmtools#1555]
Does this occur consistently?  Yes
Repro steps:

1. Open ARM template in Vs code
2.

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.15.8
OS: darwin
OS Release: 22.3.0
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:209:204152
callWithTelemetryAndErrorHandlingSync extension.bundle.js:16:248270
WrappedErrorHandler.closed extension.bundle.js:209:204035
LanguageClient.handleConnectionClosed extension.bundle.js:16:170156
LanguageClient.handleConnectionClosed extension.bundle.js:209:71022
closeHandler extension.bundle.js:16:168118
CallbackList.invoke vscode-jsonrpc/events.js:55:39
Emitter.fire vscode-jsonrpc/events.js:117:36
closeHandler vscode-jsonrpc/connection.js:256:26
CallbackList.invoke extension.bundle.js:16:310204
Emitter.fire extension.bundle.js:16:310988
StreamMessageWriter.fireClose extension.bundle.js:209:146917
Socket.<anonymous> extension.bundle.js:209:147780
```

</details>

**Comment by hemebond** [comment]
Same issue for me. July 2023 release of Visual Studio Code on MacOS.

<details>
<summary>Extension output</summary>

```
Using dotnet core executable at ***/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.20/dotnet
Starting ARM Template Language Server at ***/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.10/languageServer/Microsoft.ArmLanguageServer.dll
Language server nuget version: 3.0.0-preview.23156.3
Client options:
{
  "documentSelector": [
    {
      "language": "arm-template",
      "scheme": "file"
    },
    {
      "language": "arm-template",
      "scheme": "untitled"
    }
  ],
  "diagnosticCollectionName": "ARM Template Language Server diagnostics",
  "outputChannel": {
    "name": "Azure Resource Manager Tools",
    "extensionPrefix": "azureResourceManagerTools",
    "_outputChannel": {
      "name": "Azure Resource Manager Tools"
    }
  },
  "revealOutputChannelOn": 3,
  "synchronize": {
    "configurationSection": "azureResourceManagerTools"
  },
  "middleware": {}
}
Server options:
{
  "run": {
    "command": "***/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.20/dotnet",
    "args": [
      "***/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.10/languageServer/Microsoft.ArmLanguageServer.dll",
      "--logLevel",
      "Warning"
    ],
    "options": {
      "shell": false
    }
  },
  "debug": {
    "command": "***/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.20/dotnet",
    "args": [
      "***/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.10/languageServer/Microsoft.ArmLanguageServer.dll",
      "--logLevel",
      "Warning"
    ],
    "options": {
      "shell": false
    }
  }
}
Failed to create CoreCLR, HRESULT: 0x80004005
Error: The connection to the ARM Template Language Server got closed.
[Info  - 9:35:18 AM] Connection to server got closed. Server will restart.
Failed to create CoreCLR, HRESULT: 0x80004005
Error: The connection to the ARM Template Language Server got closed.
[Info  - 9:35:18 AM] Connection to server got closed. Server will restart.
Failed to create CoreCLR, HRESULT: 0x80004005
Error: The connection to the ARM Template Language Server got closed.
[Info  - 9:35:18 AM] Connection to server got closed. Server will restart.
Failed to create CoreCLR, HRESULT: 0x80004005
Error: The connection to the ARM Template Language Server got closed.
[Info  - 9:35:18 AM] Connection to server got closed. Server will restart.
Failed to create CoreCLR, HRESULT: 0x80004005
Error: The connection to the ARM Template Language Server got closed.
[Error - 9:35:18 AM] Connection to server got closed. Server will not be restarted.
Error: ARM Template Language Server: An error occurred starting the language server.

Connection to server got closed. Server will not be restarted.
Language server failed on start-up: ARM Template Language Server: An error occurred starting the language server.

Connection to server got closed. Server will not be restarted.: Error: ARM Template Language Server: An error occurred starting the language server.

Connection to server got closed. Server will not be restarted.
	at ***/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.10/dist/extension.bundle.js:16:294550
	at Generator.throw (<anonymous>)
	at rejected (***/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.10/dist/extension.bundle.js:16:285678)
```

</detail>
