### ISSUE TITLE
API Schemas are not updated

### ISSUE THREAD

**Issue by tshaiman** [microsoft/vscode-azurearmtools#1557]
In many of the existing resources the plugin has warnings that suggests that the API Version is not support.
in fact most chances are that the plugin metadata information is out of sync with the latest API's 

e.g : for Log Analytics workspaces it says apiVersion: "22-10-01" is not valid, while in fact that is the most up-to-date version

![image](https://user-images.githubusercontent.com/512709/221406526-5558a39e-f6bd-43b1-8e4e-12d862815654.png)

from Azure Docs : 
https://learn.microsoft.com/en-us/azure/templates/microsoft.operationalinsights/workspaces?pivots=deployment-language-arm-template

![image](https://user-images.githubusercontent.com/512709/221406571-b4347e92-71ec-4db3-86d6-9ba5499df039.png)

**Comment by StephenWeatherford** [comment]
@anthony-c-martin The latest version I see in https://schema.management.azure.com/schemas/common/autogeneratedResources.json is this:

                    "$ref": "https://schema.management.azure.com/schemas/2021-12-01-preview/Microsoft.OperationalInsights.json#/resourceDefinitions/workspaces"

Bicep is fine with 2022-10-01, though.  Any "insights"?  :-)  Thx.

**Comment by S-Tasker** [comment]
The schemas appear to have not been updated in this addon in quite a while.
I can see that the schemas exist, and have been generated in the repo here: https://github.com/Azure/azure-resource-manager-schemas/tree/main/schemas

However, they've not been imported into the Plugin for VSCode.
Example:
![image](https://user-images.githubusercontent.com/36956532/224267304-7a368181-932b-4c66-a955-8395622c2b89.png)

**Comment by StephenWeatherford** [comment]
@S-Tasker Yes I'm working on that (https://github.com/microsoft/vscode-azurearmtools/pull/1558).  In the particular case @tshaiman mentions, though, the schema update doesn't seem to fix it because the one version doesn't appear to be propagated properly to the schema root.

**Comment by StephenWeatherford** [comment]
Updated schemas will ship in next release.

Working:
  Microsoft.Storage/storageAccounts/fileServices

Still not working (due to schema issues mentioned above):
Microsoft.OperationalInsights/workspaces
<img width="567" alt="image" src="https://user-images.githubusercontent.com/6913354/225471681-4164d51f-9afa-4daa-9909-93bdd29a8ce4.png">

**Comment by anthony-c-martin** [comment]
@StephenWeatherford I've kicked off a run of https://github.com/Azure/azure-resource-manager-schemas/actions/runs/4432345621 - should hopefully shed some light on what's going on with operationalinsights.

**Comment by anthony-c-martin** [comment]
@jorgecotillo any context on this? https://github.com/Azure/azure-resource-manager-schemas/commit/f085aebf4b3f6487224a1f396a511f8e1fc60eeb

**Comment by jorgecotillo** [comment]
@anthony-c-martin there is an enum mismatch and hasn't been updated:
https://github.com/Azure/azure-rest-api-specs/blob/ee157d6bbf6e4c4fdc8a47b380e00ddd56a0e852/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2022-10-01/Tables.json#L761 -> enum vs values.

I'll create a PR in the rest-api-specs repo.

**Comment by tshaiman** [comment]
when trying to update the VS Code Plugin v0.15.9 you get an error : 
```
2023-03-23 03:31:53.644 [error] Extension 'github.copilot' wants API proposal 'interactive' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-03-23 03:31:56.154 [info] [perf] Render performance baseline is 16ms
2023-03-23 03:32:14.432 [error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {"name":"Canceled"}
2023-03-23 03:32:22.643 [error] Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/c:/Users/tshaiman/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/c:/Users/tshaiman/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/tshaiman/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-23 03:32:22.663 [error] PackageIntegrityCheckFailed: Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/c:/Users/tshaiman/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/c:/Users/tshaiman/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Users/tshaiman/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
```

**Comment by StephenWeatherford** [comment]
I saw that, too, but upon investigating it didn't seem to be related to this extension.  Can you try F1->Disable All Installed Extensions, then reenable ARM Tools and try again?

**Comment by tshaiman** [comment]
same same

**Comment by StephenWeatherford** [comment]
@tshaiman Continuing this thread here: #1572

**Comment by Philippe85** [comment]
API Schemas are not updated with last version in v0.15.10 :

![image](https://github.com/microsoft/vscode-azurearmtools/assets/25458469/7429a2e6-fdc8-451b-b622-935d67110a55)

![image](https://github.com/microsoft/vscode-azurearmtools/assets/25458469/904f26ce-3b4a-42d0-8157-25b30dc593d5)

![image](https://github.com/microsoft/vscode-azurearmtools/assets/25458469/2dcd2a35-33cc-49fa-9ed7-bee43d124330)

![image](https://github.com/microsoft/vscode-azurearmtools/assets/25458469/aad95b88-0b99-4c07-b7b4-7a01fb6f1693)

![image](https://github.com/microsoft/vscode-azurearmtools/assets/25458469/a5c1ba31-3bc8-4911-9627-e25aeae9b818)

**Comment by StephenWeatherford** [comment]
@Philippe85 Fixed in next release, thanks.

**Comment by StephenWeatherford** [comment]
Microsoft.OperationalInsights/workspaces tracked in https://github.com/microsoft/vscode-azurearmtools/issues/1628, everything else should be working in next release.
