### ISSUE TITLE
Issue when using this plugin in conjunction with a remote ADO Repo (using Remote Repos extension)

### ISSUE THREAD

**Issue by jasontenpenny** [microsoft/vscode-azurearmtools#1647]
Does this occur consistently? Yes
Repro steps:

1. I have a separate VS Code profile set up, not sure if that matters. But I only have an ARM template open in the one profile.
2. Connect to a remote Azure DevOps Repo (using the Azure Repos plugin)
3. Open a .json file that is configured with the Azure Resource Manager Template language.

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.15.11
OS: darwin
OS Release: 23.0.0
Product: Visual Studio Code
Product Version: 1.82.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:29:204152
callWithTelemetryAndErrorHandlingSync extension.bundle.js:16:248270
WrappedErrorHandler.closed extension.bundle.js:29:204035
LanguageClient.handleConnectionClosed extension.bundle.js:16:170156
LanguageClient.handleConnectionClosed extension.bundle.js:29:71022
closeHandler extension.bundle.js:16:168118
CallbackList.invoke vscode-languageserver-protocol/vscode-jsonrpc/events.js:55:39
Emitter.fire vscode-languageserver-protocol/vscode-jsonrpc/events.js:117:36
closeHandler vscode-languageserver-protocol/vscode-jsonrpc/connection.js:256:26
CallbackList.invoke extension.bundle.js:16:310204
Emitter.fire extension.bundle.js:16:310988
StreamMessageReader.fireClose extension.bundle.js:29:143245
Socket.<anonymous> extension.bundle.js:29:144905
```

</details>

<details>
<summary>Additional info from Output</summary>

```
Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at OmniSharp.Extensions.LanguageServer.Protocol.Serialization.Converters.AbsoluteUriConverter.ReadJson(JsonReader reader, Type objectType, Uri existingValue, Boolean hasExistingValue, JsonSerializer serializer)
   at Newtonsoft.Json.JsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(IMethodWithParams instance)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.GetDescriptor(Request request)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.OmniSharp.Extensions.JsonRpc.IRequestRouter<OmniSharp.Extensions.JsonRpc.IHandlerDescriptor>.GetDescriptor(Request request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.StartCallback()
Error: The connection to the ARM Template Language Server got closed.
[Info  - 3:51:22 PM] Connection to server got closed. Server will restart.
```
</details>

**Comment by StephenWeatherford** [comment]
@jasontenpenny I'm having trouble reproducing this.  For instance, I opened the following repo: https://github.com/stephenweatherford/template-examples

and opened a template file in it: apiprofile3.json

It opens fine.  I did have to manually change the language to Azure Resource Manager Template instead of json.

If I right-click on the file tab and select "Copy remote file URL", I get this: https://github.com/StephenWeatherford/template-examples/blob/55755e9cae7462210f20c75368c8315082b3f90e/apiprofile3.json

Under "additional output" above, the error given was:
```
Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
```
so I was thinking it was probably to do with the remote URL, but worked fine for me.

What's the remote URI of the file you're having trouble with?

**Comment by jasontenpenny** [comment]
@StephenWeatherford I haven't had the issue when editing GitHub files. I've only seen it when trying to edit files in Azure DevOps repositories. I believe this ability relies on the "Azure Repos" extension, so I'm guessing there's some kind of interop issue between them or something.

**Comment by Mathias8610** [comment]
@StephenWeatherford  I can reproduce the exact same behavior. The problem only occurs in connection with the "Azure Repos" extension. A fix or a workaround would be much apprecheated.

**Comment by StephenWeatherford** [comment]
What's the format of the URI you get if you right-click on the file tab and select "Copy remote file URL"?

**Comment by jasontenpenny** [comment]
I don't see that menu option, even if I try it from a local clone. Maybe I'm missing something?
![image](https://github.com/microsoft/vscode-azurearmtools/assets/50330957/ce3d1783-1456-459a-97f2-0e0171f2920b)

Something else interesting, is that the "Azure Resource Manager Template" language mode is no longer presented as an option when I'm viewing a file from a remote repository. That's something that has changed since I opened this issue, so not sure if an extension update is responsible for that or what. As a result, I can't reproduce the error messages, but I also still cannot view an ARM template from a remote repository with the proper markup.
![image](https://github.com/microsoft/vscode-azurearmtools/assets/50330957/29540a53-45ac-43aa-a137-4cd379e7b159)

Everything still appears to be working as expected when I'm using a local clone.

**Comment by StephenWeatherford** [comment]
You have to right-click on the tab, not the editor.

<img width="551" alt="image" src="https://github.com/microsoft/vscode-azurearmtools/assets/6913354/9df6d940-e983-483c-8016-783f1996af1c">

I haven't made any changes for that in the extension, but I can't investigate right now.

**Comment by jasontenpenny** [comment]
Ah ok, I figured it out. That option is enabled by the GitLens plugin, which I didn't have.

So when browsing a remote ADO repository using the "Azure Repos" plugin, the remote URL is in the following pattern: 
github.com/[Organization]/[Project]/blob/[Branch]/[Repo]/path/to/file.json.

I would expect it to be one of the following (which is what happens when doing a local clone):
[Organization].visualstudio.com/[Project]/_git/[Repo]?path=/path/to/file.json?version=GB[Branch]
dev.azure.com/[Organization]/[Project]/_git/[Repo]?path=/path/to/file.json?version=GB[Branch]

**Comment by StephenWeatherford** [comment]
Probably same isssue as https://github.com/Azure/bicep/issues/11467#issuecomment-1745503349

**Comment by StephenWeatherford** [comment]
It's looking like we're going to have to disable the Bicep extension for this scenario.
