### ISSUE TITLE
The Azure Resource Manager Template server crashed 

### ISSUE THREAD

**Issue by brysk** [microsoft/vscode-azurearmtools#328]
Repro steps:

1. Install VS code
2. Install ARM template plugin

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.7.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.31.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.t.WrappedErrorHandler.closed.n.callWithTelemetryAndErrorHandlingSync.e extension.bundle.js:218:772819
Object.module.exports.t.callWithTelemetryAndErrorHandlingSync extension.bundle.js:1:193147
WrappedErrorHandler.closed extension.bundle.js:218:772687
LanguageClient.handleConnectionClosed vscode-languageclient/client.js:2044:55
LanguageClient.handleConnectionClosed vscode-languageclient/main.js:127:15
closeHandler vscode-languageclient/client.js:2023:18
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
closeHandler vscode-jsonrpc/main.js:226:26
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
StreamMessageReader.fireClose vscode-jsonrpc/messageReader.js:111:27
Socket.listen.readable.on vscode-jsonrpc/messageReader.js:151:46
Socket.emit events.js:187:15
Pipe.Socket._destroy._handle.close [as _onclose] net.js:596:12
```

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (An exception was thrown while initializing part "Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader".) ---> Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader". ---> System.UnauthorizedAccessException: Access to the path '/Microsoft/ARMLanguageServer/Schemas/JSON' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.WebTools.Languages.Json.Schema.Cache.JsonSchemaCache..ctor(String userDataSchemaPath)
   at Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader..ctor(ILanguageHost host)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass70_1`2.<GetExports>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.ArmLanguageServer.Program.MainAsync(String[] args) in /_/Microsoft.ArmLanguageServer/Program.cs:line 48
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.ArmLanguageServer.Program.Main(String[] args) in /_/Microsoft.ArmLanguageServer/Program.cs:line 31
[Info  - 4:49:05 PM] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. (An exception was thrown while initializing part "Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader".) ---> Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader". ---> System.UnauthorizedAccessException: Access to the path '/Microsoft/ARMLanguageServer/Schemas/JSON' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.WebTools.Languages.Json.Schema.Cache.JsonSchemaCache..ctor(String userDataSchemaPath)
   at Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader..ctor(ILanguageHost host)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass70_1`2.<GetExports>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.ArmLanguageServer.Program.MainAsync(String[] args) in /_/Microsoft.ArmLanguageServer/Program.cs:line 48
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.ArmLanguageServer.Program.Main(String[] args) in /_/Microsoft.ArmLanguageServer/Program.cs:line 31
[Info  - 4:49:05 PM] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. (An exception was thrown while initializing part "Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader".) ---> Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader". ---> System.UnauthorizedAccessException: Access to the path '/Microsoft/ARMLanguageServer/Schemas/JSON' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.WebTools.Languages.Json.Schema.Cache.JsonSchemaCache..ctor(String userDataSchemaPath)
   at Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader..ctor(ILanguageHost host)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass70_1`2.<GetExports>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.ArmLanguageServer.Program.MainAsync(String[] args) in /_/Microsoft.ArmLanguageServer/Program.cs:line 48
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.ArmLanguageServer.Program.Main(String[] args) in /_/Microsoft.ArmLanguageServer/Program.cs:line 31
[Info  - 4:49:06 PM] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. (An exception was thrown while initializing part "Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader".) ---> Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader". ---> System.UnauthorizedAccessException: Access to the path '/Microsoft/ARMLanguageServer/Schemas/JSON' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.WebTools.Languages.Json.Schema.Cache.JsonSchemaCache..ctor(String userDataSchemaPath)
   at Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader..ctor(ILanguageHost host)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass70_1`2.<GetExports>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.ArmLanguageServer.Program.MainAsync(String[] args) in /_/Microsoft.ArmLanguageServer/Program.cs:line 48
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.ArmLanguageServer.Program.Main(String[] args) in /_/Microsoft.ArmLanguageServer/Program.cs:line 31
[Info  - 4:49:07 PM] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. (An exception was thrown while initializing part "Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader".) ---> Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader". ---> System.UnauthorizedAccessException: Access to the path '/Microsoft/ARMLanguageServer/Schemas/JSON' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.WebTools.Languages.Json.Schema.Cache.JsonSchemaCache..ctor(String userDataSchemaPath)
   at Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader..ctor(ILanguageHost host)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass70_1`2.<GetExports>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.ArmLanguageServer.Program.MainAsync(String[] args) in /_/Microsoft.ArmLanguageServer/Program.cs:line 48
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.ArmLanguageServer.Program.Main(String[] args) in /_/Microsoft.ArmLanguageServer/Program.cs:line 31
[Error - 4:49:08 PM] Connection to server got closed. Server will not be restarted.

```
</details>

**Comment by StephenWeatherford** [comment]
@bhsubra @alexgav Where does WebTools try to create the cache folder?  Do we know we have permissions?

**Comment by alexgav** [comment]
public string UserFolder
        {
            get {
                string localAppData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
                return Path.Combine(localAppData, "Microsoft", "ARMLanguageServer");
            }
        }

        public string SchemasFolder
        {
            get
            {
                string jsonSchemaCachePath = Path.Combine(UserFolder, "Schemas");
                return jsonSchemaCachePath;
            }
        }

**Comment by alexgav** [comment]
We didn't have an issue with that before - on either Linux or Mac. This hasn't changed recently. Not sure why we are getting this now.

**Comment by StephenWeatherford** [comment]
@brysk Did this only happen once, or does it happen consistently?

**Comment by brysk** [comment]
@StephenWeatherford it happens consistently, ARM Template Language Server is stuck starting.

**Comment by StephenWeatherford** [comment]
Any idea why local application data would fail to resolve?  Anything unusual about your setup?

>            string localAppData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
>            return Path.Combine(localAppData, "Microsoft", "ARMLanguageServer");

**Comment by StephenWeatherford** [comment]
According to https://johnkoerner.com/csharp/special-folder-values-on-windows-versus-mac/, it should resolve to /Users/<user>/.config

**Comment by alexgav** [comment]
Actually to /Users/username/.local/share since it's LocalApplicationData

**Comment by StephenWeatherford** [comment]
@brysk So, to summarize...  Please see if the folder $HOME/.local/share exists on your machine, and if not, create it and try again.  Thx!

**Comment by brysk** [comment]
@StephenWeatherford once I have created $HOME/.local/share folder plugin can be initialised properly. I can see Microsoft folder inside share, no more errors. Thank you

**Comment by StephenWeatherford** [comment]
Good to know, thanks!  We believe we have a fix, which will go out in the next release.
cc @alexgav

**Comment by StephenWeatherford** [comment]
https://github.com/microsoft/vscode-azurearmtools/issues/332

**Comment by neilpeterson** [comment]
Fix went out today with this fix, thanks.
