### ISSUE TITLE
Azure Resource Manager Template server crashed - Language Server Error

### ISSUE THREAD

**Issue by rupanter** [microsoft/vscode-azurearmtools#404]
Repro steps:

1. Open VS Code
2. Open a ARM File

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.8.2
OS: darwin
Product: Visual Studio Code - Insiders
Product Version: 1.41.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:745913
Object.t.callWithTelemetryAndErrorHandlingSync extension.bundle.js:1:217466
WrappedErrorHandler.closed extension.bundle.js:218:745781
LanguageClient.handleConnectionClosed vscode-languageclient/client.js:2044:55
LanguageClient.handleConnectionClosed vscode-languageclient/main.js:127:15
closeHandler vscode-languageclient/client.js:2023:18
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
closeHandler vscode-jsonrpc/main.js:226:26
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
StreamMessageReader.fireClose vscode-jsonrpc/messageReader.js:111:27
Socket.<anonymous> vscode-jsonrpc/messageReader.js:151:46
Socket.emit events.js:205:15
Pipe.<anonymous> net.js:586:12
```

</details>

Error from the Log :

Unhandled Exception: System.AggregateException: One or more errors occurred. (An exception was thrown while initializing part "Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader".) ---> Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader". ---> System.UnauthorizedAccessException: Access to the path '/Users/rupanterchhabra/.local/share/Microsoft/ARMLanguageServer/Schemas/JSON' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.WebTools.Languages.Json.Schema.Cache.JsonSchemaCache..ctor(String userDataSchemaPath)
   at Microsoft.WebTools.Languages.Json.Arm.Schema.ArmCachingJsonDocumentLoader..ctor(ILanguageHost host)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass70_1`2.<GetExports>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.ArmLanguageServer.Program.MainAsync(String[] args) in /_/Microsoft.ArmLanguageServer/Program.cs:line 50
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.ArmLanguageServer.Program.Main(String[] args) in /_/Microsoft.ArmLanguageServer/Program.cs:line 33
[Error - 4:35:21 PM] Connection to server got closed. Server will not be restarted.

---------------------------
Tried checking the folder at the location it's trying to find : 
'/Users/rupanterchhabra/.local/share/Microsoft/ARMLanguageServer/Schemas/JSON' is denied. ---> System.IO.IOException: Permission denied

The folder doesn't exist : 
PS /Users/rupanterchhabra/.local/share> ls
powershell
PS /Users/rupanterchhabra/.local/share>

---------------------------
Have tried uninstalling and re-installing the Extension.

**Comment by StephenWeatherford** [comment]
@Rupanter Chhabra This should have been fixed in version 0.8.0.  I’ve verified it successfully creates the folders for me on 0.8.2.  You said you tried creating the folders manually.  Did it successfully create the folder?

I.e., open the “terminal” app and try this:

mkdir -p /Users/rupanterchhabra/.local/share/Microsoft/ARMLanguageServer/Schemas/JSON

Is the folder successfully created?  Does the extension work at that point?

Thx,
Stephen

**Comment by rupanter** [comment]
@StephenWeatherford 
I tried creating the folders manually and it didn’t work.
 
One thing to note is, I couldn’t create using the normal cmd :
mkdir -p /Users/rupanterchhabra/.local/share/Microsoft/ARMLanguageServer/Schemas/JSON
 
Rupanters-MBP:share rupanterchhabra$ mkdir -p /Users/rupanterchhabra/.local/share/Microsoft/ARMLanguageServer/Schemas/JSON
mkdir: /Users/rupanterchhabra/.local/share/Microsoft/ARMLanguageServer/Schemas/JSON: Permission denied
 
Rupanters-MBP:share rupanterchhabra$ mkdir -p 'Microsoft/ARMLanguageServer/Schemas/JSON'
mkdir: Microsoft/ARMLanguageServer/Schemas/JSON: Permission denied
 
I had to use sudo to create it :
Sudo mkdir -p /Users/rupanterchhabra/.local/share/Microsoft/ARMLanguageServer/Schemas/JSON
Rupanters-MBP:share rupanterchhabra$ sudo mkdir -p /Users/rupanterchhabra/.local/share/Microsoft/ARMLanguageServer/Schemas/JSON
Rupanters-MBP:share rupanterchhabra$
 
Could this be causing the problem? That the extension is unable to create/access the location because of root permissions?
Even after having the folders using the sudo, the language server is still crashing.

**Comment by StephenWeatherford** [comment]
For those following this issue, Rupanter's ~/.local folder was owned by root instead of rupanter.  That likely means some process being run as root was the one that created it (don't know how this happened exactly).  The fix was to fix the owner of these folders by running
```
sudo chown -R $USER: ~/.local
```

**Comment by StephenWeatherford** [comment]
Note: Need to provide link to diagnostic wiki in our errors.

**Comment by StephenWeatherford** [comment]
The workaround is documented here: https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition
