### ISSUE TITLE
VSCode repeatedly reports ARM Templates Server connection errors 

### ISSUE THREAD

**Issue by amillion8** [microsoft/vscode-azurearmtools#411]
Repro steps:

1.
2.

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.8.2
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:745913extension.bundle.js:218:745913
Object.t.callWithTelemetryAndErrorHandlingSync extension.bundle.js:1:217466
WrappedErrorHandler.closed extension.bundle.js:218:745781
LanguageClient.handleConnectionClosed vscode-languageclient/client.js:2044:55
LanguageClient.handleConnectionClosed vscode-languageclient/main.js:127:15
closeHandler vscode-languageclient/client.js:2023:18
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
closeHandler vscode-jsonrpc/main.js:226:26
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
StreamMessageReader.fireClose vscode-jsonrpc/messageReader.js:111:27
Socket.<anonymous> vscode-jsonrpc/messageReader.js:151:46
Socket.emit events.js:205:15
Pipe.<anonymous> net.js:586:12
```

</details>

**Comment by StephenWeatherford** [comment]
@amillion8 Could you check if there's more error information in the Output window (View->Output), in the "Azure Resource Manager Tools" or "Azure Resource Manager Template" tabs?
![image](https://user-images.githubusercontent.com/6913354/70569832-8a9af980-1b4f-11ea-80b5-2f468addd7ad.png)
Thx.

**Comment by amillion8** [comment]
@StephenWeatherford  Below is the content of the Output window:

Using dotnet core executable at c:\Users\ZH543TE\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5\dotnet.exe
Starting ARM Template Language Server at c:\Users\ZH543TE\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.8.2\languageServer\Microsoft.ArmLanguageServer.dll
Language server nuget version: 3.0.0-preview.19558.3
Client options:
{
  "documentSelector": [
    {
      "language": "arm-template",
      "scheme": "file"
    }
  ],
  "diagnosticCollectionName": "ARM Template Language Server diagnostics",
  "revealOutputChannelOn": 3
}
Server options:
{
  "run": {
    "command": "c:\\Users\\ZH543TE\\AppData\\Roaming\\Code\\User\\globalStorage\\msazurermtools.azurerm-vscode-tools\\.dotnet\\2.2.5\\dotnet.exe",
    "args": [
      "c:\\Users\\ZH543TE\\.vscode\\extensions\\msazurermtools.azurerm-vscode-tools-0.8.2\\languageServer\\Microsoft.ArmLanguageServer.dll",
      "--logLevel",
      "Warning"
    ],
    "options": {
      "shell": false
    }
  },
  "debug": {
    "command": "c:\\Users\\ZH543TE\\AppData\\Roaming\\Code\\User\\globalStorage\\msazurermtools.azurerm-vscode-tools\\.dotnet\\2.2.5\\dotnet.exe",
    "args": [
      "c:\\Users\\ZH543TE\\.vscode\\extensions\\msazurermtools.azurerm-vscode-tools-0.8.2\\languageServer\\Microsoft.ArmLanguageServer.dll",
      "--logLevel",
      "Warning"
    ],
    "options": {
      "shell": false
    }
  }
}
Error: The connection to the ARM Template Language Server got closed.
Error: The connection to the ARM Template Language Server got closed.
Error: The connection to the ARM Template Language Server got closed.
Error: The connection to the ARM Template Language Server got closed.
Error: The connection to the ARM Template Language Server got closed.

**Comment by StephenWeatherford** [comment]
Thanks but what about the Azure Resource Manager Template pane?


-------- Original message --------

**Comment by amillion8** [comment]
This is from the Azure Resource Manager plane:

![image](https://user-images.githubusercontent.com/58707355/70655735-63f7c400-1c1e-11ea-9da1-9e8a70430261.png)

**Comment by StephenWeatherford** [comment]
Should be one for Azure Resource Manager Tools (the extension, one for Azure Resource Manager Template (the language server):
<img width="326" alt="image" src="https://user-images.githubusercontent.com/6913354/70662370-ec746580-1c1a-11ea-9838-9fd09d6a3a10.png">

**Comment by amillion8** [comment]
Here is the output from Azure Resource Manager Template pane:

[Info  - 10:34:11 AM] Finding descriptor for initialize
[Info  - 10:34:11 AM] Starting: Routing Request (0) initialize
[Info  - 10:34:11 AM] Converting params for Request (0) initialize to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams
[Info  - 10:34:11 AM] Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult, OmniSharp.Extensions.LanguageProtocol, Version=0.12.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
[Info  - 10:34:11 AM] Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult
[Info  - 10:34:11 AM] Finished: Routing Request (0) initialize in 68ms
[Info  - 10:34:11 AM] Finding descriptor for initialized
[Info  - 10:34:11 AM] Starting: Routing Notification initialized
[Info  - 10:34:11 AM] Converting params for Notification initialized to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams

Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value "file://d.docs.live.net@ssl/DavWWWRoot/6604279be68b6e11/Documents/Work/Azure/ARM%20Templates/hdinsight/template-hdi-spark-esp-combined.json" to type 'System.Uri'. Path 'params.textDocument.uri', line 1, position 221. ---> System.ArgumentException: Could not cast or convert from System.String to System.Uri.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[Info  - 10:34:12 AM] Connection to server got closed. Server will restart.
[Info  - 10:34:16 AM] Finding descriptor for initialize
[Info  - 10:34:16 AM] Starting: Routing Request (0) initialize
[Info  - 10:34:16 AM] Converting params for Request (0) initialize to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams
[Info  - 10:34:17 AM] Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult, OmniSharp.Extensions.LanguageProtocol, Version=0.12.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
[Info  - 10:34:17 AM] Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult
[Info  - 10:34:17 AM] Finished: Routing Request (0) initialize in 74ms
[Info  - 10:34:17 AM] Finding descriptor for initialized
[Info  - 10:34:17 AM] Starting: Routing Notification initialized
[Info  - 10:34:17 AM] Converting params for Notification initialized to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams

Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value "file://d.docs.live.net@ssl/DavWWWRoot/6604279be68b6e11/Documents/Work/Azure/ARM%20Templates/hdinsight/template-hdi-spark-esp-combined.json" to type 'System.Uri'. Path 'params.textDocument.uri', line 1, position 221. ---> System.ArgumentException: Could not cast or convert from System.String to System.Uri.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[Info  - 10:34:17 AM] Connection to server got closed. Server will restart.
[Info  - 10:34:22 AM] Finding descriptor for initialize
[Info  - 10:34:22 AM] Starting: Routing Request (0) initialize
[Info  - 10:34:22 AM] Converting params for Request (0) initialize to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams
[Info  - 10:34:22 AM] Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult, OmniSharp.Extensions.LanguageProtocol, Version=0.12.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
[Info  - 10:34:22 AM] Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult
[Info  - 10:34:22 AM] Finished: Routing Request (0) initialize in 91ms
[Info  - 10:34:22 AM] Finding descriptor for initialized
[Info  - 10:34:22 AM] Starting: Routing Notification initialized
[Info  - 10:34:22 AM] Converting params for Notification initialized to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams

Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value "file://d.docs.live.net@ssl/DavWWWRoot/6604279be68b6e11/Documents/Work/Azure/ARM%20Templates/hdinsight/template-hdi-spark-esp-combined.json" to type 'System.Uri'. Path 'params.textDocument.uri', line 1, position 221. ---> System.ArgumentException: Could not cast or convert from System.String to System.Uri.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[Info  - 10:34:22 AM] Connection to server got closed. Server will restart.
[Info  - 10:34:27 AM] Finding descriptor for initialize
[Info  - 10:34:27 AM] Starting: Routing Request (0) initialize
[Info  - 10:34:27 AM] Converting params for Request (0) initialize to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams
[Info  - 10:34:27 AM] Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult, OmniSharp.Extensions.LanguageProtocol, Version=0.12.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
[Info  - 10:34:27 AM] Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult
[Info  - 10:34:27 AM] Finished: Routing Request (0) initialize in 57ms
[Info  - 10:34:27 AM] Finding descriptor for initialized
[Info  - 10:34:27 AM] Starting: Routing Notification initialized
[Info  - 10:34:27 AM] Converting params for Notification initialized to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams

Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value "file://d.docs.live.net@ssl/DavWWWRoot/6604279be68b6e11/Documents/Work/Azure/ARM%20Templates/hdinsight/template-hdi-spark-esp-combined.json" to type 'System.Uri'. Path 'params.textDocument.uri', line 1, position 221. ---> System.ArgumentException: Could not cast or convert from System.String to System.Uri.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[Info  - 10:34:27 AM] Connection to server got closed. Server will restart.
[Info  - 10:34:32 AM] Finding descriptor for initialize
[Info  - 10:34:32 AM] Starting: Routing Request (0) initialize
[Info  - 10:34:32 AM] Converting params for Request (0) initialize to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams
[Info  - 10:34:32 AM] Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult, OmniSharp.Extensions.LanguageProtocol, Version=0.12.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
[Info  - 10:34:32 AM] Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult
[Info  - 10:34:32 AM] Finished: Routing Request (0) initialize in 56ms
[Info  - 10:34:32 AM] Finding descriptor for initialized
[Info  - 10:34:32 AM] Starting: Routing Notification initialized
[Info  - 10:34:32 AM] Converting params for Notification initialized to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams

Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value "file://d.docs.live.net@ssl/DavWWWRoot/6604279be68b6e11/Documents/Work/Azure/ARM%20Templates/hdinsight/template-hdi-spark-esp-combined.json" to type 'System.Uri'. Path 'params.textDocument.uri', line 1, position 221. ---> System.ArgumentException: Could not cast or convert from System.String to System.Uri.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[Error - 10:34:33 AM] Connection to server got closed. Server will not be restarted.

**Comment by StephenWeatherford** [comment]
@amillion8 Are you still seeing this issue?  Thanks.

**Comment by amillion8** [comment]
No, I switched to using PyCharm.
