### ISSUE TITLE
Extension is installed and it doesn't load

### ISSUE THREAD

**Issue by fgauna12** [Microsoft/vscode-azurearmtools#45]
I'm using version 0.4.0
Windows 10 x64
VS Code Version: 1.21.1 x64

I used to be able to rename my arm template parameters with F2.
Now F2 doesn't work.

I can't also jump to definition. 
I don't have intellisense either.

I don't know how to troubleshoot why my extension is not loading and why.
Best I can find on the Output console is this

```
[2018-03-20 09:50:40.409] [exthost1] [info] ExtensionService#_doActivateExtension msazurermtools.azurerm-vscode-tools {"startup":false,"activationEvent":"onLanguage:json"}
```

Update: I toggled developer tools and found the following console error:

```
console.ts:136 [Extension Host] Activating extension `msazurermtools.azurerm-vscode-tools` failed:  Cannot find module 'open'

[Extension Host] Here is the error stack:  Error: Cannot find module 'open'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:784)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\FacundoGauna\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.4.0\out\src\AzureRMTools.js:12:14)
	at Object.<anonymous> (C:\Users\FacundoGauna\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.4.0\out\src\AzureRMTools.js:602:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
```

**Comment by StephenWeatherford** [comment]
@fgauna12 Have you uninstalled/reinstalled?  If yes, what OS are you on and what version of VSCode (insiders?).

**Comment by fgauna12** [comment]
I have tried uninstalling it and reinstalling it.
I am on Windows 10.
VS Code Version: 1.21.1

**Comment by StephenWeatherford** [comment]
Is VSCode 32-bit or 64-bit?

**Comment by fgauna12** [comment]
64 bit

**Comment by StephenWeatherford** [comment]
I can't repro it. @EricJizbaMSFT have you seen anything like this? I know we had this issue on Linux, but not on Windows.

**Comment by EricJizbaMSFT** [comment]
Yeah I've seen occasional failures like this. I don't know the cause, but my only other suggestion is the following:
1. Make sure the extension is installed
1. Navigate to VS Code's extensions folder (Probably something like this: `C:\Users\<user name>\.vscode\extensions\`)
1. Delete the specific extension's folder (Probably named `msazurermtools.azurerm-vscode-tools-0.4.0`)
1. Re-install the extension

**Comment by fgauna12** [comment]
Thanks! That worked!
To be more specific: I deleted the folder, also restarted VS Code, then installed the extension, then restarted VS Code.

**Comment by StephenWeatherford** [comment]
Good to know how to fix, thanks @fgauna12 and @EricJizbaMSFT
