### ISSUE TITLE
"Cannot read property 'start' of undefined: TypeError: Cannot read property 'start' of undefined" in suites

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#858]

**Comment by StephenWeatherford** [comment]
https://github.com/microsoft/vscode/issues/99410

    at t.intersection (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:433:799)
    at D.provideCodeActions (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:670:551)
    at d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:631
    at K._withAdapter (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:686:499)
    at K.$provideCodeActions (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:609)
    at m._doInvokeHandler (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:801:683)
    at m._invokeHandler (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:801:375)
    at m._receiveRequest (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:953)
    at m._receiveOneMessage (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:798:832)
    at d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:34
    at l.fire (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
    at v.fire (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:235:849)
    at d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:975:744
    at l.fire (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
    at v.fire (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:235:849)
    at t.PersistentProtocol._receiveMessage (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:276)
    at d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:237:357
    at l.fire (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
    at p.acceptChunk (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:233:393)
    at d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:232:753
    at Socket.t (d:\a\1\s\.vscode-test\vscode-1.47.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:241:826)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
